### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by RobinMalfait** [andrew8088/dome#2]
I don't want to be rude or something but i see that you use something == "undefined"

but WHAT if a stupid dude does this:

var undefined = true;

than your code is fucked up, right? so replace this

window.dome = (function () {

with

window.dome = (function (undefined) {

so now you know that it's undefined :)

**Comment by andrew8088** [comment]
Actually, no. What I'm doing is this:

```
typeof someArg !== 'undefined'
```

If an argument is not provided to a function, it will be `undefined`; when using the `typeof` operator with an `undefined` value, it returns the string "undefined". So, even if someone overwrites `undefined`, my code will work fine.
